language: php
sudo: false

php:
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make legestue_net.build ../legestue-dev.net
  - cd ../legestue-dev.net
  - chmod -R 777 sites/
  - drush si legestue_net --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="legestue.net" --yes
  - drush cc all --yes

script: 
  - test -d profiles/legestue_net
  - test -d profiles/legestue_net/modules/contrib
